apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruning-my-pothos
  namespace: {{ .Values.namespace }} # Placeholder for namespace
  labels:
    app: pruning-my-pothos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pruning-my-pothos
  template:
    metadata:
      labels:
        app: pruning-my-pothos
    spec:
      containers:
        - name: web
          image: ghcr.io/shaileshrawat1403/pruning-my-pothos-website:{{ .Values.imageTag }} # Placeholder for image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: # Added resource limits and requests
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe: # Added liveness probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe: # Added readiness probe
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
