apiVersion: v1
kind: Service
metadata:
  name: pruning-my-pothos
  namespace: {{ .Values.namespace }} # Placeholder for namespace
  labels:
    app: pruning-my-pothos
spec:
  selector:
    app: pruning-my-pothos
  type: LoadBalancer # Changed to LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
